- name: Expense Project Setup
  hosts: all
  tasks:
    - name: Installing Nginx
      ansible.builtin.dnf:
        name: nginx
        state: present
    - name: Copy Expense Config File
      ansible.builtin.copy:
        src: expense.conf
        dest: /etc/nginx/default.d/expense.conf
    - name: Clean Old Nginx Directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: absent
    - name: Create Nginx Directory
      ansible.builtin.file:
        path: /usr/share/nginx/html
        state: directory
    - name: Download And Extract Frontend Files
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/frontend.zip
        dest: /usr/share/nginx/html
        remote_src: yes
    - name: Starting Nginx
      ansible.builtin.systemd:
        name: nginx
        state: restart
        enabled: yes
