- name: Disable Nodejs Default Version
  ansible.builtin.shell: dnf module disable nodejs -y
- name: Enable Nodejs !8 Version
  ansible.builtin.shell: dnf module enable nodejs:18 -y
- name: Install Nodejs
  ansible.builtin.dnf:
    name: nodejs
    state: present
- name: Copy Backend Files
  ansible.builtin.copy:
    src: backend.service
    dest: /etc/systemd/system/backend.service
- name: Add Application User
  ansible.builtin.user:
    name: expense
- name: Delete Old App
  ansible.builtin.file:
    path: /app
    state: absent
- name: Create app Direcroy
  ansible.builtin.file:
    path: /app
    state: directory
- name: Download and Extract
  ansible.builtin.unarchive:
    src: https://expense-artifacts.s3.amazonaws.com/backend.zip
    dest: /app
    remote_src: yes
- name: Download Nodejs Dependencies
  ansible.builtin.shell: npm install
  args:
    chdir: /app
- name: Install my sql client
  ansible.builtin.dnf:
    name: mysql
    state: present
- name: Load Schema
  ansible.builtin.shell: mysql -h 172.31.35.22 -uroot -pExpenseApp@1 < /app/schema/backend.sql &>/tmp/expense.log
- name: Start backend Services
  ansible.builtin.systemd:
    name: backend
    state: restarted
    enabled: yes
    daemon-reload: yes