- name: Installing Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present
- name: Copy Expense Config File
  ansible.builtin.copy:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import Common Role
  ansible.builtin.import_role:
    name: common
    tasks_from: pre_require
  vars:
    app_dir: /usr/share/nginx/html
    common_file: frontend

- name: Starting Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: import elk role filebeat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat
